env:
  - HUGO_VERSION="0.55.6"

before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -O hugo.tar.gz
  - tar -zxvf hugo.tar.gz
  - npm install

script:
  - npm run css
  - npm run js
  - ./hugo
  - npm run html
  - echo "richardkapicka.cz" > public/CNAME
  - echo "/css/*" >> public/.gitignore
  - echo "/js/*" >> public/.gitignore

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local_dir: public
